apiVersion: v1
kind: Namespace
metadata:
  name: atlas-gateway
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-core
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-intel
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-ml
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-data
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-infra
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-monitoring
  labels:
    app.kubernetes.io/part-of: atlas
    environment: production
